# Generated by Django 2.1.7 on 2019-09-09 20:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='课程名称')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='课程难度')),
                ('introduction', models.CharField(default='这个课程没有简介', max_length=255, verbose_name='课程简介')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='课程描述')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='courses/courses/covers/', verbose_name='课程封面')),
                ('recommend', models.CharField(choices=[('yes', '推荐到首页'), ('no', '不推荐到首页')], max_length=3, verbose_name='推荐')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论量')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类别名称', max_length=30, verbose_name='类别名称')),
                ('code', models.CharField(help_text='类别代码', max_length=30, verbose_name='类别代码')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, help_text='父级类目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.CourseCategory', verbose_name='父级类目')),
            ],
            options={
                'verbose_name': '课程类别',
                'verbose_name_plural': '课程类别',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseCategory', verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.School', verbose_name='授课机构'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Teacher', verbose_name='授课教师'),
        ),
    ]
