# Generated by Django 2.1.7 on 2019-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('add_time',), 'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('add_time',), 'verbose_name': '博客类别', 'verbose_name_plural': '博客类别'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ('add_time',), 'verbose_name': '博客标签', 'verbose_name_plural': '博客标签'},
        ),
    ]
